name: build
on: [workflow_call, push]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.workflow == 'publish' || !contains(github.event.head_commit.message, '[skip build]') }}
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run build
      - run: cd examples/my-app && npm ci --ignore-scripts
      - run: npm run lint
      - run: npm t
      - run: npm run typecheck-test
      - run: cd examples/my-app && npm run typecheck
      - uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - run: npm run type-coverage
      - name: persist to workspace
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/*
